# Generated by Django 4.1.1 on 2022-09-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspace',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectspace',
            name='space',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectSpace',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
